language: go
go:
 - 1.x
 - tip

env:
  - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - mkdir -p $GOPATH/src/github.com/graymeta
  - cd $GOPATH/src/github.com/graymeta
  - git clone https://github.com/appscode/stow.git
  - cd stow
  - dep ensure -vendor-only

script:
  - cd $GOPATH/src/github.com/graymeta/stow
  - go build ./...
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
